# Generated by Django 4.1.13 on 2024-11-14 08:09

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='', max_length=100)),
                ('session_id', models.CharField(default='', max_length=100)),
                ('session_start_time', models.DateTimeField()),
                ('session_end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('inst_name', models.CharField(max_length=100)),
                ('session_duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('userEmail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('token', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, null=True)),
                ('display_name', models.CharField(max_length=100)),
                ('attended_time', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='googleMeet.session')),
            ],
        ),
    ]
