# Generated by Django 4.1.13 on 2024-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branchname', models.CharField(max_length=100)),
            ],
        ),
    ]
