# Generated by Django 4.1.13 on 2024-10-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetsessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='studentsinvited',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='videoLink',
            field=models.URLField(default=''),
        ),
    ]
