# Generated by Django 4.1.13 on 2024-11-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetsessions', '0002_session_ended_session_studentsinvited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
