# Generated by Django 4.1.13 on 2024-08-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.TextField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('scopes', models.JSONField()),
                ('universe_domain', models.TextField()),
                ('account', models.TextField(blank=True, null=True)),
                ('expiry', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='GoogleOAuth2Credentials',
        ),
    ]
