# Generated by Django 4.1.13 on 2024-08-28 10:55

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_credentials_delete_googleoauth2credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('userEmail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('token', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
